apiVersion: batch/v1
kind: Job
metadata:
  name: hive-init-schema
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hive-schema-init
          image: vishalpancholi/spark-delta:v3
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Starting Hive schema initialization...";
              /init-hive-metastore.sh
          env:
            - name: HIVE_METASTORE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: jdbc-url
            - name: HIVE_METASTORE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: HIVE_METASTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password