---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
  labels:
    app: prometheus-pushgateway
spec:
  selector:
    app: prometheus-pushgateway
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
  labels:
    app: prometheus-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pushgateway
  template:
    metadata:
      labels:
        app: prometheus-pushgateway
    spec:
      containers:
        - name: prometheus-pushgateway
          image: prom/pushgateway:v1.6.2 # Use a recent stable version
          ports:
            - containerPort: 9091
              name: http