apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: spark

type: Opaque
data:
  # To encode: echo -n "your-value" | base64
  # Example: your-mysql-server.mysql.database.azure.com
  host: c3BhcmstaG1zLW15c3FsLXNlcnZlci5teXNxbC5kYXRhYmFzZS5henVyZS5jb20=
  database: aGl2ZV9tZXRhc3RvcmU=
  username: bXlzcWxhZG1pbg==
  password: <replace this password base64 encoded with your password>
  # Example: jdbc:mysql://spark-hms-mysql-server.mysql.database.azure.com:3306/hive_metastore
  jdbc-url: amRiYzpteXNxbDovL3NwYXJrLWhtcy1teXNxbC1zZXJ2ZXIubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29tOjMzMDYvaGl2ZV9tZXRhc3RvcmU=
  accesskey: <replace this access key base64 encoded>
